---
title: "1.a_LoadEnv"
output: html_document
date: "2023-07-16"
---
```{r set the boundary}
#crop the environmental layers first based on the boundaries of each state
#Northernmost point: 71.24°N (Alaska)
#Southernmost point: 22.89°N (Baja California Sur)
#Westernmost point: 172.45°E (Alaska)
#Easternmost point: 109.27°W (Baja California)
extent.1=extent(c(-180,-109,22,72))
extent.2=extent(c(172,180,22,72))
#a new crs is set in order to center merge the two parts of Alaska that were separated by 180 °E 180°W
crs<-CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +lon_0=-100")
```
```{r wrld_simpl}
data(wrld_simpl)
wrld_simpl.1=crop(wrld_simpl,extent.1)
wrld_simpl.2=crop(wrld_simpl,extent.2)
wrld_simpl.cb=merge(wrld_simpl.1,wrld_simpl.2)
wrld_simpl.new<-spTransform(wrld_simpl.cb,crs)
```
```{r Load WorldClim, cache=TRUE, warning=FALSE}
#Load Bioclimatic variables from WordClim.com
WorldClim=getData("worldclim", var="bio", res=2.5)
# rescale data using gain()
gain(WorldClim) <- 0.1
#WorldClim.new<-spTransform(WorldClim,crs)
WorldClim.1=crop(WorldClim,extent.1)
WorldClim.2=crop(WorldClim,extent.2)
WorldClim.cb=merge(WorldClim.2,WorldClim.1)
names(WorldClim.cb)<-names(WorldClim.1)
```
```{r NALCMS landcover}
#load landcover type tif
landcover<-raster("input/land_cover_2020_30m_tif/NA_NALCMS_landcover_2020_30m.tif")
#reproject the entire layer
landcover.lonlat<-projectRaster(landcover,WorldClim,method="ngb")
landcover.lonlat.1<-crop(landcover.lonlat,WorldClim.1)
landcover.lonlat.2<-crop(landcover.lonlat,WorldClim.2)
landcover.lonlat.crop<-merge(landcover.lonlat.2,landcover.lonlat.1)
plot(landcover.lonlat.crop)
#add water type to all null category
landcover.sup<-reclassify(landcover.lonlat.crop,matrix(c(0,18),ncol=2))
plot(landcover.sup)
colortable(landcover.sup)<-colortable(landcover)
plot(landcover.sup)
```
```{r coastline and elevation}
#load other cropped raster 
coast.distance<-raster("input/GMT_intermediate_coast_distance_01d.tif")
coast.distance.1=crop(coast.distance,WorldClim.1)
coast.distance.2=crop(coast.distance,WorldClim.2)
coast.distance.crop=merge(coast.distance.2,coast.distance.1)
coast.distance.lonlat<-projectRaster(coast.distance.crop,WorldClim.cb)

elev.1<-get_elev_raster(WorldClim.1,z=8)
elev.2<-get_elev_raster(WorldClim.2,z=8)
elev.lonlat.1<-projectRaster(elev.1,WorldClim.cb)
elev.lonlat.2<-projectRaster(elev.2,WorldClim.cb)
elev.crop<-merge(elev.lonlat.2,elev.lonlat.1)
```
```{r stack together}
#stack the raster layers together
WorldClim.cb=stack(WorldClim.cb,landcover.sup,coast.distance.lonlat,elev.crop)
names(WorldClim.cb)<-c(names(WorldClim),"landcover.type","d.coastline","elevation")
#test plot
plot(WorldClim.cb$d.coastline)
```
