---
title: "LoadBG"
author: "Xuewen Geng"
date: '2022-06-21'
output: html_document
---
```{r Load Parameters}
library(auk)
#Set parameters for data cleaning, based on Best Practices for Using eBird Data (Strimas-Mackey et al. 2023)
#set years of interest parameter
years=2010:2023
#set breeding season (June, July) as date parameter
dates=c("*-06-01","*-07-31")
#set country ranges, limited to North America
countries=c("US","CA","Mexico")
#set observation duration as 0 min to 360 min
durations=c(0,360)
#set distance as 0 km to 10 km
distances=c(0,10)
#set protocol as Stationary and Traveling
protocols=c("Stationary", "Traveling")
#set starting time as 6:00-21:00
starttime=(start_time=c("06:00","21:00"))
#set spatial box to remove outliers in each species
#the spatial boxes are defined by the localities of ebird occurrence point. 
#Outliers are occurrence points that are too far away from other occurrence points. 
bbox_bg=c(-175,31,-114,62)
```
```{r Load Ebird Data}
#read occurrence data from Canada: British Columbia, Yukon Territory
CA_BC<-"input/ebd_CA-BC_relMay-2023.txt"
f_out <- "data/ebd_filtered_CA-BC.txt"
filters <- auk_ebd(CA_BC)%>%
  auk_date(date=dates)%>%
  auk_year(year=years)%>%
  auk_bbox(bbox=bbox_bg)%>%
  auk_duration(duration=durations)%>%
  auk_distance(distance=distances)%>%
  auk_protocol(protocol=protocols)%>%
  auk_time(start_time = starttime)%>%
  auk_complete()
filtered<- auk_filter(filters, file = f_out,overwrite=TRUE)
CA_BC<-read_ebd(filtered)

CA_YT<-"input/ebd_CA-YT_relMay-2023.txt"
f_out <- "data/ebd_filtered_CA-YT.txt"
filters <- auk_ebd(CA_YT)%>%
  auk_date(date=dates)%>%
  auk_year(year=years)%>%
  auk_bbox(bbox=bbox_bg)%>%
  auk_duration(duration=durations)%>%
  auk_distance(distance=distances)%>%
  auk_protocol(protocol=protocols)%>%
  auk_time(start_time = starttime)%>%
  auk_complete()
filtered<- auk_filter(filters, file = f_out,overwrite=TRUE)
CA_YT<-read_ebd(filtered)

#read occurrence data from US: Alaska, California, Oregon, Washington
US_OR<-"input/ebd_US-OR_relMay-2023.txt"
f_out <- "data/ebd_filtered_US-OR.txt"
filters <- auk_ebd(US_OR)%>%
  auk_date(date=dates)%>%
  auk_year(year=years)%>%
  auk_bbox(bbox=bbox_bg)%>%
  auk_duration(duration=durations)%>%
  auk_distance(distance=distances)%>%
  auk_protocol(protocol=protocols)%>%
  auk_time(start_time = starttime)%>%
  auk_complete()
filtered<- auk_filter(filters, file = f_out,overwrite=TRUE)
US_OR <- read_ebd(filtered)

US_AK<-"input/ebd_US-AK_relMay-2023.txt"
f_out <- "data/ebd_filtered_US-AK.txt"
filters <- auk_ebd(US_AK)%>%
  auk_date(date=dates)%>%
  auk_year(year=years)%>%
  auk_bbox(bbox=bbox_bg)%>%
  auk_duration(duration=durations)%>%
  auk_distance(distance=distances)%>%
  auk_protocol(protocol=protocols)%>%
  auk_time(start_time = starttime)%>%
  auk_complete()
filtered<- auk_filter(filters, file = f_out,overwrite=TRUE)
US_AK <- read_ebd(filtered)

US_CA<-"input/ebd_US-CA_relMay-2023.txt"
f_out <- "data/ebd_filtered_US-CA.txt"
filters <- auk_ebd(US_CA)%>%
  auk_date(date=dates)%>%
  auk_year(year=years)%>%
  auk_bbox(bbox=bbox_bg)%>%
  auk_duration(duration=durations)%>%
  auk_distance(distance=distances)%>%
  auk_protocol(protocol=protocols)%>%
  auk_time(start_time = starttime)%>%
  auk_complete()
filtered<- auk_filter(filters, file = f_out,overwrite=TRUE)
US_CA <- read_ebd(filtered)

US_WA<-"input/ebd_US-WA_relMay-2023.txt"
f_out <- "data/ebd_filtered_US-WA.txt"
filters <- auk_ebd(US_WA)%>%
  auk_date(date=dates)%>%
  auk_year(year=years)%>%
  auk_bbox(bbox=bbox_bg)%>%
  auk_duration(duration=durations)%>%
  auk_distance(distance=distances)%>%
  auk_protocol(protocol=protocols)%>%
  auk_time(start_time = starttime)%>%
  auk_complete()
filtered<- auk_filter(filters, file = f_out,overwrite=TRUE)
US_WA <- read_ebd(filtered)

#Load occurrence data from Mexico: Baja California and Baja California Sur
MX_BCN<-"input/ebd_MX-BCN_relMay-2023.txt"
f_out <- "data/ebd_filtered_US-BCN.txt"
filters <- auk_ebd(MX_BCN)%>%
  auk_date(date=dates)%>%
  auk_year(year=years)%>%
  auk_bbox(bbox=bbox_bg)%>%
  auk_duration(duration=durations)%>%
  auk_distance(distance=distances)%>%
  auk_protocol(protocol=protocols)%>%
  auk_time(start_time = starttime)%>%
  auk_complete()
filtered<- auk_filter(filters, file = f_out,overwrite=TRUE)
MX_BCN <- read_ebd(filtered)
```
```{r sampling}
r=sample(length(CA_BC$checklist_id),round(length(CA_BC$checklist_id)/100))
CA_BC=CA_BC[r,]
plot(wrld_simpl.cb)
points(CA_BC$longitude,CA_BC$latitude)

r=sample(length(CA_YT$checklist_id),round(length(CA_YT$checklist_id)/100))
CA_YT=CA_YT[r,]
plot(wrld_simpl.cb)
points(CA_YT$longitude,CA_YT$latitude)

r=sample(length(US_AK$checklist_id),round(length(US_AK$checklist_id)/100))
US_AK=US_AK[r,]
plot(wrld_simpl.cb)
points(US_AK$longitude,US_AK$latitude)

r=sample(length(US_OR$checklist_id),round(length(US_OR$checklist_id)/100))
US_OR=US_OR[r,]
plot(wrld_simpl.cb)
points(US_OR$longitude,US_OR$latitude)

r=sample(length(US_WA$checklist_id),round(length(US_WA$checklist_id)/100))
US_WA=US_WA[r,]
plot(wrld_simpl.cb)
points(US_WA$longitude,US_WA$latitude)

r=sample(length(US_CA$checklist_id),round(length(US_CA$checklist_id)/100))
US_CA=US_CA[r,]
plot(wrld_simpl.cb)
points(US_CA$longitude,US_CA$latitude)

r=sample(length(MX_BCN$checklist_id),round(length(MX_BCN$checklist_id)/100))
MX_BCN=MX_BCN[r,]
plot(wrld_simpl.cb)
points(MX_BCN$longitude,MX_BCN$latitude)

BG=rbind.data.frame(CA_BC,CA_YT,US_OR,US_WA,US_CA,US_AK,MX_BCN)
plot(wrld_simpl.cp)
points(BG$longitude,BG$latitude)
```
```{r create BG points}
BG=BG[which(BG$number_observers<=10),]
r=sample(length(BG$scientific_name),30000)
BG.r=BG[r,]
thin(BG.r,lat.col = "latitude",long.col = "longitude",spec.col = "common_name",thin.par=0.5,reps=1,out.dir = "./data",out.base = "bg_thin")
BG.thin<-read.csv("data/bg_thin_thin1.csv",header=TRUE,)
thin.r=sample(length(BG.thin$long),10000)
BG.thin.r=BG.thin[thin.r,]


WorldClim.bg=raster::extract(WorldClim.cb,cbind(BG.thin.r$long,BG.thin.r$lat),df=TRUE)
bg.check=cbind(longitude=BG.thin.r$long,latitude=BG.thin.r$lat,WorldClim.bg)
any(is.na(bg.check))
bg.check=bg.check[!is.na(bg.check$bio1),]
bg.check=bg.check[!is.na(bg.check$landcover.type),]

plot(wrld_simpl.cp)
points(bg.check$longitude,bg.check$latitude)
BG.lonlat<-cbind(longitude=bg.check$longitude,latitude=bg.check$latitude)
```