---
title: "Untitled"
output: html_document
date: "2023-04-03"
---
```{r cars}
library(auk)
library(ggplot2)
library(ggmap)
library(dismo)
library(maptools)
library(ggpubr)
```
```{r Fig.4 jackknife plot}

#Load model results from maxent model outputs
modelResult<-read.csv(paste0(".//output//glwgul_maxent//maxentResults.csv"))
jack<-as.data.frame(t(modelResult[,44:75][11,]))
modelResult<-read.csv(paste0(".//output//wesgul_maxent//maxentResults.csv"))
jack<-rbind(jack,as.data.frame(t(modelResult[,44:75][11,])))
modelResult<-read.csv(paste0(".//output//hybgul_maxent//maxentResults.csv"))
jack<-rbind(jack,as.data.frame(t(modelResult[,44:75][11,])))
colnames(jack)="value"

#Label variables
jack$variable<-rep(rep(c("Barren Lands","Annual Mean Temperature","Annual Precipitation","Mean Diurnal Range","Temperature Seasonality","Cropland","Distance to Coastline","Elevation","Mixed forest","Snow and Ice","Temperate or sub-polar broadleaf deciduous forest","Temperate or sub-polar grassland","Temperate or sub-polar needleleaf forest","Temperate or sub-polar shrubland","Urban","Wetland"),2),3)
jack$tag<-rep(c(rep("without",16),rep("with only", 16)),3)
jack$species<-rep(c("glaucous-winged gull","western gull","hybrid gull"),each=32)

#Plot
ggplot(jack)+
  geom_col(aes(value,variable,fill=tag),position="dodge")+
  facet_wrap(~species,scales = "free_x")+
  labs(fill="",x="",y="")+
  theme_light()
```
```{r Fig.5 responsecurve plot}
variable_list<-names(WorldClim.sr)

wg.plot<-vector("list",16)
gg.plot<-vector("list",16)
hg.plot<-vector("list",16)

#Load and store response curve results from maxent models
for(s in 1:16){
  #For Western gulls:
  dat<-read.csv(paste0(".//output//wesgul_maxent//plots//species_",variable_list[s],"_only.dat"))
  list= list.files(path=".//output//wesgul_maxent//plots",pattern=paste0("species_\\d_",variable_list[s],"_only.dat"))
  list=lapply(paste0(".//output//wesgul_maxent//plots//",list), read.csv)
  c=cbind(list[[1]]$y,list[[2]]$y,list[[3]]$y,list[[4]]$y,list[[5]]$y,list[[6]]$y,list[[7]]$y,list[[8]]$y,list[[9]]$y,list[[10]]$y)
  sd=apply(c,1,sd)
sd=cbind(x=list[[1]]$x,sd)
x=merge(dat,sd,by="x")
wg.plot[[s]]<-x
  #For Glaucous-winged gulls:
  dat<-read.csv(paste0(".//output//glwgul_maxent//plots//species_",variable_list[s],"_only.dat"))
  list<-list.files(path=".//output//glwgul_maxent//plots",pattern=paste0("species_\\d_",variable_list[s],"_only.dat"))
  list=lapply(paste0(".//output//glwgul_maxent//plots//",list), read.csv)
  c=cbind(list[[1]]$y,list[[2]]$y,list[[3]]$y,list[[4]]$y,list[[5]]$y,list[[6]]$y,list[[7]]$y,list[[8]]$y,list[[9]]$y,list[[10]]$y)
  sd=apply(c,1,sd)
sd=cbind(x=list[[1]]$x,sd)
x=merge(dat,sd,by="x")
gg.plot[[s]]<-x
  #For Hybrid gulls: 
  dat<-read.csv(paste0(".//output//hybgul_maxent//plots//species_",variable_list[s],"_only.dat"))
  list<-list.files(path=".//output//hybgul_maxent//plots",pattern=paste0("species_\\d_",variable_list[s],"_only.dat"))
  list<-lapply(paste0(".//output//hybgul_maxent//plots//",list), read.csv)
  c=cbind(list[[1]]$y,list[[2]]$y,list[[3]]$y,list[[4]]$y,list[[5]]$y,list[[6]]$y,list[[7]]$y,list[[8]]$y,list[[9]]$y,list[[10]]$y)
  sd=apply(c,1,sd)
sd=cbind(x=list[[1]]$x,sd)
x=merge(dat,sd,by="x")
hg.plot[[s]]<-x
}

#Labels
labs<-c("Annual Mean Temperature","Mean Diurnal Range","Temperature Seasonality","Annual Precipitation","Temperate or sub-polar needleleaf forest","Temperate or sub-polar grassland","Wetland","Urban","Cropland","Barren Lands","Snow and Ice", "Temperate or sub-polar broadleaf deciduous forest","Mixed forest","Temperate or sub-polar shrubland","Distance to Coastline","Elevation")
g<-vector("list",16)

for(s in 1:16){
  g[[s]]<-ggplot()+
  geom_line(data=hg.plot[[s]],aes(x=x,y=y,color="Hybrids"),size=1)+
  geom_ribbon(data=hg.plot[[s]],aes(x=x,ymin=y-sd,ymax=y+sd,fill="hybrids"),alpha=0.2)+
  geom_line(data=gg.plot[[s]],aes(x=x,y=y,color="Glaucous-winged gull"),size=1,linetype=4)+
  geom_ribbon(data=gg.plot[[s]],aes(x=x,ymin=y-sd,ymax=y+sd,fill="glaucous-winged gull"),alpha=0.2)+
  geom_line(data=wg.plot[[s]],aes(x=x,y=y,color="Western gull"),size=1, linetype=3)+
  geom_ribbon(data=wg.plot[[s]],aes(x=x,ymin=y-sd,ymax=y+sd,fill="Western gull"),alpha=0.2)+
  labs(colour="Species",x=labs[s],y="")+
  scale_color_brewer(palette = "Set2")+
  scale_fill_brewer(palette="Set2")+
  theme_light()+
  theme(axis.title.x=element_text(size=10))+
  guides(fill=FALSE,colour = guide_legend(override.aes = list(linetype =c(4,1,3)
)))
}
#Combine and rearrange plots
plot<-ggarrange(g[[1]],g[[2]],g[[3]],g[[4]],g[[5]],g[[6]],g[[7]],g[[8]],g[[9]],g[[10]],g[[11]],g[[12]],g[[13]],g[[14]],g[[15]],g[[16]],labels=c("A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P"),ncol=4,nrow=4,common.legend=TRUE,legend = "bottom")
plot
annotate_figure(plot,left=text_grob("Model predicted probability of occurrence",rot=90))
```

